# Site settings
title: Alex J. Schenk | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."
url: "https://ajs1592.github.io/emerald/"
author:
  name: "Alex J. Schenk"
  email: "alexjschenk@gmail.com"
  url: "https://ajs1592.github.io/emerald/"

# Build settings
baseurl: /emerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
